Repository fossasia/open-event-attendee-android, pull requests merged in 2019-11, with the labels that each got.

#2396 chore: improve bash script for release
  scripts/prep-key.sh
  scripts/update-apk.sh
Labels: chore

#2418 fix: App crash on search results fragment
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
Labels: fix

#2422 chore(deps): bump stripe-android from 12.2.0 to 12.3.0
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
Labels: dependencies

#2429 chore(deps): bump com.diffplug.gradle.spotless from 3.25.0 to 3.26.0
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
Labels: dependencies

#2427 feat: Remove useless native binaries from paypal SDK (#2426)
  app/build.gradle
Labels: feature

#2416 fix: Add prices in for all tickets in TicketIdAndQty
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
Labels: fix

#2431 fix: UI conflict in ticket section
  app/src/main/res/layout/fragment_orders_under_user.xml
Labels: fix
