Repository fossasia/open-event-attendee-android, pull requests merged in 2019-05, with the labels that each got.

#1695 chore: refractor to use RxExtensions
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/about/AboutEventViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/faq/EventFAQViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/utils/extensions/RxExtensions.kt
  app/src/playStore/java/org/fossasia/openevent/general/search/GeoLocationViewModel.kt
  app/src/playStore/java/org/fossasia/openevent/general/welcome/WelcomeViewModel.kt
Labels: chore

#1690 refactor: refactor to use data binding
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/utils/DataBindingAdapters.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/fragment_event.xml
Labels: chore, refactor

#1702 feat: Add sharing ticket feature
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt
  app/src/main/res/layout-land/item_card_order_details.xml
  app/src/main/res/layout/item_card_order_details.xml
  app/src/main/res/menu/order_detail.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1711 fix: Change the QR value based on server
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
Labels: fix

#1717 chore: Bump version code and name for release v0.2.1
  app/build.gradle
Labels: chore

#1716 fix: app crash on navigating Similar Event Detail
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/4.json
  app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#1735 fix: Reloading events onBackPressed after search
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#1736 fix: Remove overlapping animation conflicts
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#1727 feat: Add enlarged QR Image + Increase brightness
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/QrCode.kt
  app/src/main/res/layout-land/item_card_order_details.xml
  app/src/main/res/layout/item_card_order_details.xml
  app/src/main/res/layout/item_enlarged_qr.xml
Labels: feature

#1742 fix: Retain chip state on screen rotation in SearchResultFragment
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
Labels: fix

#1743 feat: Add empty view for FAQ section
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/faq/EventFAQFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/faq/EventFAQViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/res/drawable/ic_faq.xml
  app/src/main/res/layout/fragment_event_faq.xml
  app/src/main/res/layout/fragment_events.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1693 feat: Add session fragment
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/1.json
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/5.json
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/common/RecyclerViewCallbacks.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/Session.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionDao.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionService.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/microlocation/MicroLocation.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/microlocation/MicroLocationConverter.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/sessiontype/SessionType.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/sessiontype/SessionTypeConverter.kt
  app/src/main/res/drawable/ic_language_black.xml
  app/src/main/res/layout/fragment_session.xml
  app/src/main/res/layout/item_session.xml
  app/src/main/res/layout/item_speaker.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: feature

#1754 feat: Update settings and profile fragment for non authenticated users
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings.xml
Labels: feature

#1747 fix: Updating feedback section after making new one
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/feedback/FeedbackRecyclerAdapter.kt
  app/src/main/res/values/strings.xml
Labels: fix

#1757 feat: Add delete user photo feature
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/res/values/strings.xml
Labels: feature

#1756 fix: Retain searchview state in SearchFragment
  app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/res/menu/search.xml
Labels: fix

#1759 fix: Reset default value for order
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/Order.kt
Labels: fix

#1622 feat: Notification Fragment
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/notification/Notification.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationApi.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationService.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationsViewHolder.kt
  app/src/main/res/drawable/ic_notifications_none.xml
  app/src/main/res/drawable/ic_notifications_white.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/item_card_notification.xml
  app/src/main/res/layout/placeholder_item_card_notification.xml
  app/src/main/res/menu/events.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values-bn-rIN/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1765 feat: Update google smart lock with new updated password
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsViewModel.kt
Labels: feature

#1758 feat: Add LeakCanary for debug implementation
  app/build.gradle
Labels: feature

#1771 chore: bump gradle from 3.3.2 to 3.4.1
  app/src/main/java/org/fossasia/openevent/general/search/PlaceSuggestionsAdapter.kt
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: chore

#1770 chore: Bump Koin 1.0.2 to version 2.0.0-GA4
  app/build.gradle
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/5.json
  app/src/fdroid/java/org/fossasia/openevent/general/di/FlavorSpecificModules.kt
  app/src/fdroid/java/org/fossasia/openevent/general/search/GeoLocationViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/OpenEventGeneral.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/playStore/java/org/fossasia/openevent/general/di/FlavorSpecificModules.kt
  app/src/test/java/org/fossasia/openevent/general/DependencyTest.kt
Labels: chore

#1777 chore: Bump spotless from 3.16.0 to 3.23.0 and fix the violations
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorService.kt
  app/src/main/java/org/fossasia/openevent/general/utils/extensions/RxExtensions.kt
  app/src/playStore/java/org/fossasia/openevent/general/auth/SmartAuthViewModel.kt
Labels: chore

#1753 fix: Show only upcoming or ongoing events
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
Labels: fix

#1740 fix: Refractor EventDetailsFragment
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt
  app/src/main/java/org/fossasia/openevent/general/social/SocialLinksRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorRecyclerAdapter.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/fragment_similar_events.xml
  app/src/main/res/layout/fragment_social_links.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values/strings.xml
Labels: fix

#1761 fix: Retain ticket locally when logged in
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/Attendee.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeDao.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/ListAttendeeIdConverter.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDao.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/order/Order.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDao.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketIdConverter.kt
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#1783 feat: Add track for event
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/di/Scopes.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/Session.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionApi.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/track/Track.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/track/TrackConverter.kt
  app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt
  app/src/main/res/drawable/ic_track.xml
  app/src/main/res/layout/fragment_session.xml
  app/src/main/res/layout/item_session.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1763 feat: Change authentication process and remove navigation (#1749)
  app/src/fdroid/java/org/fossasia/openevent/general/auth/SmartAuthViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthApi.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/CheckEmailResponse.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_auth.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
  app/src/playStore/java/org/fossasia/openevent/general/auth/SmartAuthViewModel.kt
Labels: feature

#1788 feat: Add speakers under session
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerApi.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerService.kt
  app/src/main/res/layout/fragment_session.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1790 chore: Bump version code and name for release v0.3.0
  app/build.gradle
Labels: chore

#1792 feat: Add call for speaker section
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/6.json
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventApi.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCall.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallDao.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallViewModel.kt
  app/src/main/res/drawable/ic_speakers_call.xml
  app/src/main/res/drawable/ic_speakers_call_closed.xml
  app/src/main/res/drawable/ic_speakers_call_open.xml
  app/src/main/res/layout/fragment_speakers_call.xml
  app/src/main/res/menu/event_details.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1688 feat: Add shared element transition
  app/src/main/java/org/fossasia/openevent/general/common/RecyclerViewCallbacks.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsListAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/utils/DataBindingAdapters.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/menu/search.xml
Labels: feature

#1766 fix: Remove click listeners to remove memory leaks
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt
Labels: fix

#1797 fix: Add crashed on selecting location from welcome fragment
  app/src/main/res/navigation/navigation_graph.xml
  app/src/playStore/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
Labels: fix

#1707 fix: updated favourites on event navigation & continuous topic api calls
  app/src/main/java/org/fossasia/openevent/general/event/EventDao.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
Labels: fix

#1802 fix: app crashes on screen rotation in TicketsFragment
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Labels: fix

#1806 fix: crash on coming back from AuthFragment
  app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#1807 fix: Fix shared element transition problems for older version
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/utils/extensions/FragmentExt.kt
Labels: fix

#1799 fix: Load event detail UI immediately on EventDetailsFragment
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Labels: fix

#1812 fix: Retrieve stripe api key from build config
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
Labels: fix

#1814 fix(ui): Profile fragment and Navigation
  app/src/main/res/color/navigation_item.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/dimens.xml
Labels: fix, ui

#1820 fix: Make ticket options updatable
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
Labels: fix

#1821 feat: Add skip button
  app/src/fdroid/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/res/layout-land/fragment_welcome.xml
  app/src/main/res/layout/fragment_events.xml
  app/src/main/res/layout/fragment_welcome.xml
  app/src/main/res/values/strings.xml
  app/src/playStore/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
Labels: feature

#1810 fix: Improve AttendeesFragment
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketDao.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketService.kt
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/values/strings.xml
Labels: fix

#1834 fix: Avoid app crash on login API version <= 24
  app/build.gradle
Labels: fix

#1826 fix: Improve navigation with AuthFragment
  app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
Labels: fix

#1828 fix: Retain chip state and search results after re-selecting the chip
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
Labels: fix

#1840 fix: Make search filter fragment scrollable
  app/src/main/res/layout/fragment_search_filter.xml
Labels: fix

#1837 feat: Add code of conduct
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/codeofconduct/ConductCodeFragment.kt
  app/src/main/res/layout/fragment_conduct_code.xml
  app/src/main/res/menu/event_details.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1844 feat: Update Check-in status in orders
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
  app/src/main/res/drawable/circle_shape.xml
  app/src/main/res/layout/item_card_order_details.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1847 fix(ui): Order under user fragment
  app/src/main/res/layout/fragment_orders_under_user.xml
Labels: fix, ui

#1841 feat: Add offline payment methods
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1850 feat: Add billing information section
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/Order.kt
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1835 feat: Add filter for sessions and speakers
  app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_search_filter.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1854 fix: App crashes on registering free tickets
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
Labels: fix

#1859 feat: Add checking required fields
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/utils/StringUtils.kt
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/layout/item_attendee.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1851 feat: Show date and time wise check-in
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/6.json
  app/src/main/java/org/fossasia/openevent/general/attendees/Attendee.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
  app/src/main/res/layout/item_card_order_details.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1852 fix: Navigation to tickets form order completed fragment
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
  app/src/main/res/layout/fragment_order_completed.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#1860 fix: Add payment mode
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
Labels: fix

#1862 fix: Wrong event URL is being shared
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
  app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt
Labels: fix

#1864 fix: Ticket registration form
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/values/strings.xml
Labels: fix
