Repository fossasia/open-event-attendee-android, pull requests merged in 2019-08, with the labels that each got.

#2211 feat: Turn spinner into radio button for payment options
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/res/drawable/ic_bank.xml
  app/src/main/res/drawable/ic_cash.xml
  app/src/main/res/drawable/ic_cheque.xml
  app/src/main/res/drawable/ic_credit_card.xml
  app/src/main/res/drawable/ic_paypal.xml
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#2190 feat: Add edit/remove/take image for speaker profile photo
  app/src/main/java/org/fossasia/openevent/general/speakercall/EditSpeakerFragment.kt
  app/src/main/res/navigation/navigation_graph.xml
Labels: feature

#2188 feat: Add autolink to text
  app/src/main/java/org/fossasia/openevent/general/about/AboutEventFragment.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationsViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerFragment.kt
  app/src/main/res/layout/fragment_about_event.xml
  app/src/main/res/layout/fragment_session.xml
  app/src/main/res/layout/fragment_speaker.xml
Labels: feature

#2204 fix: Apply new discount code routing
  app/src/main/java/org/fossasia/openevent/general/discount/DiscountApi.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketService.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
Labels: fix

#2231 chore: Baseline master into dev
  scripts/update-apk.sh
Labels: chore

#2226 chore: Replace screenshots with resolution 1080 by 1920 pixels
  README.md
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_1.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_1.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_2.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_3.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_3.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_4.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_5.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_5.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_6.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_6.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_7.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_7.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_8.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_8.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_9.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_9.png
  scripts/update-apk.sh
Labels: chore

#2229 fix: Null check for ticket url
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Labels: fix

#2232 fix: Add checkbox for enabling billing information
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#2237 fix: Included tax for tickets
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
Labels: fix

#2245 fix: Change Order Now/Register Button in TicketsFragment
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
  app/src/main/res/values/strings.xml
Labels: fix

#2170 feat: Add custom form for speakers and sessions
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/8.json
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionApi.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionService.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/EditSpeakerFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/EditSpeakerViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/Proposal.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallProposalFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallProposalViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/form/SessionIdentifier.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/form/SpeakerIdentifier.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/Speaker.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerApi.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerService.kt
  app/src/main/res/layout/fragment_proposal_speaker.xml
  app/src/main/res/layout/fragment_speakers_call_proposal.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2246 fix: Number format exception for donation amount
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt
Labels: fix

#2249 fix: Location in welcome fragment
  app/src/main/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
Labels: fix

#2248 fix: Change button text to "REGISTER" for offline payment options
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
Labels: fix

#2203 fix: New profile image editable
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt
Labels: fix

#2251 fix: Prevent no donation
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
Labels: fix

#2244 fix: Improve invalid fields
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/9.json
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/EditSpeakerFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallProposalFragment.kt
  app/src/main/java/org/fossasia/openevent/general/utils/StringUtils.kt
  app/src/main/res/layout/fragment_attendee.xml
Labels: fix

#2263 fix: Email and URL validation
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
Labels: fix

#2260 fix: Add Pay Now button based on payment method
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
Labels: fix

#2259 fix: App crash when no location found
  app/src/fdroid/java/org/fossasia/openevent/general/search/location/LocationServiceImpl.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/playStore/java/org/fossasia/openevent/general/search/location/LocationServiceImpl.kt
Labels: fix

#2266 fix: Hide map when no information is present
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Labels: fix

#2265 feat: Add ticket currency for ticket detail
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
Labels: feature

#2272 fix: policy URL links
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings.xml
Labels: fix

#2269 fix: Add error utils, fix stripe error message and charge data class
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/Charge.kt
  app/src/main/java/org/fossasia/openevent/general/utils/Error.kt
  app/src/main/java/org/fossasia/openevent/general/utils/ErrorUtils.kt
  app/src/main/java/org/fossasia/openevent/general/utils/HttpErrors.kt
  app/src/main/java/org/fossasia/openevent/general/utils/StringUtils.kt
Labels: fix

#2276 fix: Hide notification Icon when user is not logged in
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
Labels: fix

#2186 feat: Add slide up down animation
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallProposalFragment.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/fragment_session.xml
  app/src/main/res/layout/fragment_speakers_call_proposal.xml
Labels: feature

#2283 fix: Invalid event's timezone for sessions
  app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationsViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewHolder.kt
Labels: Urgent, fix

#2287 fix: Handle unverified account error
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: Urgent, fix

#2294 fix: Multiple small enhancements in Event Detail Fragment
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallFragment.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorsDetailAdapter.kt
  app/src/main/res/layout/fragment_speaker.xml
  app/src/main/res/layout/fragment_speakers_call.xml
  app/src/main/res/layout/item_session.xml
  app/src/main/res/layout/item_sponsor_detail.xml
  app/src/main/res/values/strings.xml
Labels: fix

#2278 fix: pop message called multiple times
  app/src/fdroid/java/org/fossasia/openevent/general/search/location/GeoLocationViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/StartupViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/about/AboutEventViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/faq/EventFAQViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/EditSpeakerViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallProposalFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallProposalViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/utils/extensions/LiveDataExtensions.kt
  app/src/main/res/values/strings.xml
Labels: fix

#2284 chore: Version code, name and changelog for minor release 0.7.0
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/14.txt
Labels: chore

#2302 fix: Add missing text view in Item Card Detail
  app/src/main/res/layout-land/item_card_order_details.xml
Labels: fix

#2304 fix: tickets expired at wrong time
  app/src/main/java/org/fossasia/openevent/general/order/OrderDataSource.kt
Labels: fix

#2308 fix: Check unverified user with error source
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/utils/Error.kt
  app/src/main/java/org/fossasia/openevent/general/utils/ErrorUtils.kt
Labels: fix

#2223 feat: Add paypal
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt
  app/src/main/java/org/fossasia/openevent/general/paypal/Paypal.kt
  app/src/main/java/org/fossasia/openevent/general/paypal/PaypalApi.kt
  app/src/main/java/org/fossasia/openevent/general/paypal/PaypalPaymentResponse.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/res/values/strings.xml
Labels: feature

#2296 fix(ui): Align ticket details in center
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
  app/src/main/res/layout/fragment_order_details.xml
  app/src/main/res/layout/item_card_order_details.xml
Labels: fix, ui

#2310 fix: Make name not mandatory and add progress dialog in edit profile
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/res/layout/fragment_edit_profile.xml
Labels: fix

#2281 feat: Save tickets to DB
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/9.json
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDao.kt
  app/src/main/java/org/fossasia/openevent/general/order/ExpiredOrderFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/Order.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDao.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDataSource.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDataSourceFactory.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
  app/src/main/res/layout/fragment_expired_order.xml
  app/src/main/res/layout/fragment_orders_under_user.xml
Labels: feature

#2300 feat: Save attendees to DB
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/9.json
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/Attendee.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeConverter.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeId.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeIdConverter.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/ListAttendeeConverter.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/order/Order.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt
Labels: feature

#2315 chore: Remove suggestion form from settings and README
  README.md
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
  app/src/main/res/values-bn-rIN/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings.xml
Labels: chore

#2316 chore: Update description for fastlane metadata
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/short_description.txt
Labels: chore

#2321 chore: Update README and CONTRIBUTING guidelines
  CONTRIBUTING.md
  README.md
Labels: chore
