Repository fossasia/open-event-attendee-android, pull requests merged in 2019-06, with the labels that each got.

#1876 fix: Progress in Attendee fragment
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/res/layout/fragment_attendee.xml
Labels: fix

#1816 feat: Add create/load speaker profile for user
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/6.json
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/UserIdConverter.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/EditSpeakerFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/EditSpeakerViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallProposalFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallProposalViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/Speaker.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerApi.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerDao.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerService.kt
  app/src/main/res/drawable/ic_bio.xml
  app/src/main/res/drawable/ic_email.xml
  app/src/main/res/drawable/ic_expand_icon.xml
  app/src/main/res/drawable/ic_organization.xml
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/drawable/ic_position.xml
  app/src/main/res/drawable/ic_website.xml
  app/src/main/res/layout/fragment_proposal_speaker.xml
  app/src/main/res/layout/fragment_speakers_call_proposal.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1878 feat: Set up similar events in order completed fragment
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedViewModel.kt
  app/src/main/res/layout/fragment_order_completed.xml
  app/src/main/res/layout/placeholder_item_card_similar_events.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: feature

#1843 feat: Add time counter on ordering ticket
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/6.json
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/Event.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/res/drawable/border_background_ticket_timer.xml
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1883 feat: Set ticket buyer details non editable
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
Labels: feature

#1884 fix: Order cancel alert dialog
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
Labels: fix

#1888 chore(deps): Bump koin_version to 2.0.1
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/OpenEventGeneral.kt
  app/src/test/java/org/fossasia/openevent/general/DependencyTest.kt
Labels: dependencies

#1871 feat: Handle app link intent for events
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventApi.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
Labels: feature

#1889 fix: Sign Up not working
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpViewModel.kt
Labels: Urgent, fix

#1890 fix: Improve AttendeeFragment
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/values-bn-rIN/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values/strings.xml
Labels: fix

#1891 feat: Filter call for speakers event
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/6.json
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/event/Event.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventApi.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallConverter.kt
  app/src/main/res/layout/fragment_search_filter.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: feature

#1894 fix: Handle progress in event details fragment
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
Labels: fix

#1901 fix: invalid email in AuthFragment
  app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUp.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpViewModel.kt
  app/src/main/res/layout/fragment_auth.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#1903 fix: Update progress on error in event details
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
Labels: fix

#1905 feat: Add profile verification
  app/src/main/java/org/fossasia/openevent/general/auth/AuthApi.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ResendVerificationEmailResponse.kt
  app/src/main/res/drawable/ic_tick_inside_circle.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1908 fix: Ticket/order detail UI
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
  app/src/main/res/layout-land/item_card_order_details.xml
  app/src/main/res/layout/fragment_order_details.xml
  app/src/main/res/layout/item_card_order_details.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values/dimens.xml
Labels: fix

#1919 fix: Avoid crash on OrderCompleted
  app/src/main/java/org/fossasia/openevent/general/common/RecyclerViewCallbacks.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#1924 fix: crash on sign up
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/res/layout/fragment_signup.xml
Labels: fix

#1922 fix: Order completed to events navigation
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#1918 fix: Revalidate profile from API
  app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt
Labels: enhancement, fix

#1917 chore: Bump preference from alpha01 to beta01 and fix errors
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
Labels: chore, dependencies

#1902 fix: Display valid information about sessions, speakers, call for speakers
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerApi.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerService.kt
Labels: fix

#1930 feat: Add user details under editing section
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1936 fix: wrong title name in fragments
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
Labels: fix

#1933 feat: Improve Feedback section
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/6.json
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/feedback/Feedback.kt
  app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackApi.kt
  app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackDao.kt
  app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackFragment.kt
  app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackService.kt
  app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackViewModel.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/fragment_feedback.xml
  app/src/main/res/layout/item_feedback.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1916 chore: Bump stripe from 9.1.1 to 9.2.0 and fix errors
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
Labels: dependencies

#1942 fix: Multiple crashes in event details due to app link data
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Labels: fix

#1940 feat: Display tag for already registered tickets
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1939 feat: Improve UI in EventsFragment, OrdersFragment, FavoriteFragment
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/ExpiredOrderFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/res/drawable/background_fragment.xml
  app/src/main/res/drawable/ic_event.xml
  app/src/main/res/layout/content_no_tickets.xml
  app/src/main/res/layout/fragment_events.xml
  app/src/main/res/layout/fragment_expired_order.xml
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/fragment_orders_under_user.xml
  app/src/main/res/menu/events.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1947 chore: Upload screenshots and load them form the repo
  README.md
  docs/images/ic_fdroid.png
  docs/images/ic_play_store.png
  docs/images/screenshot_1.png
  docs/images/screenshot_2.png
  docs/images/screenshot_3.png
  docs/images/screenshot_4.png
  docs/images/screenshot_5.png
  docs/images/screenshot_6.png
  docs/images/screenshot_7.png
  docs/images/screenshot_8.png
  docs/images/screenshot_9.png
Labels: chore

#1925 feat: Set up downloading invoice
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/invoice/DownloadInvoiceService.kt
  app/src/main/res/menu/order_detail.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1957 fix: Shimmer layout is overlapping tickets
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
Labels: fix

#1956 fix: Blank order details fragment
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
  app/src/main/res/values/strings.xml
Labels: fix

#1959 fix: Progress dialog is continued showing on error in attendee fragment
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
Labels: fix

#1785 fix: Database declaration warning by Travis build
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerWithEventDao.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorWithEventDao.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorsDetailAdapter.kt
Labels: fix

#1863 feat: Implement Stripe and charging
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/res/values/strings.xml
Labels: feature

#1961 feat: Add data binding to recycler/adapter
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsListAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/event/similarevent/SimilarEventViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/event/similarevent/SimilarEventsListAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/utils/DataBindingAdapters.kt
  app/src/main/res/layout-land/item_card_order_details.xml
  app/src/main/res/layout/item_card_events.xml
  app/src/main/res/layout/item_card_favorite_event.xml
  app/src/main/res/layout/item_card_order.xml
  app/src/main/res/layout/item_card_order_details.xml
  app/src/main/res/layout/item_card_similar_events.xml
Labels: feature

#1958 fix: Events fragment UI
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_events.xml
  app/src/main/res/values/strings.xml
Labels: fix

#1969 fix: sharing event by URL
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/event/similarevent/SimilarEventViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
  app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt
Labels: fix

#1950 feat: Improve Search Section
  app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTimeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/res/drawable/background_fragment_search.xml
  app/src/main/res/drawable/ic_arrow_back_black.xml
  app/src/main/res/drawable/ic_baseline_tick.xml
  app/src/main/res/drawable/ic_search_white.xml
  app/src/main/res/layout-land/fragment_search.xml
  app/src/main/res/layout/event_type_list.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_filter.xml
  app/src/main/res/layout/fragment_search_location.xml
  app/src/main/res/layout/fragment_search_results.xml
  app/src/main/res/layout/fragment_search_time.xml
  app/src/main/res/layout/fragment_search_type.xml
  app/src/main/res/menu/search_filter.xml
  app/src/main/res/menu/search_results.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1978 fix: Make name field editable in Attendee fragment
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
Labels: fix

#1977 fix: Check for device location settings
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt
Labels: fix

#1973 feat: Add signout/login while ordering ticket
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1982 feat: Add search edit text in SearchResultFragment
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/res/drawable/ic_clear.xml
  app/src/main/res/layout/fragment_search_results.xml
Labels: feature

#1988 feat: Check for new notifications
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/7.json
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/notification/Notification.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationApi.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationDao.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationService.kt
  app/src/main/res/drawable/ic_circle.xml
  app/src/main/res/layout/fragment_events.xml
Labels: feature

#1960 feat: Implement option to apply discount codes
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/discount/DiscountApi.kt
  app/src/main/java/org/fossasia/openevent/general/discount/DiscountCode.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketService.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
  app/src/main/res/layout/fragment_tickets.xml
  app/src/main/res/layout/item_ticket.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1972 fix: custom form implementation
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/7.json
  app/src/main/java/org/fossasia/openevent/general/attendees/Attendee.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeApi.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeDao.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeService.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/forms/CustomForm.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/forms/FormIdentifier.kt
  app/src/main/java/org/fossasia/openevent/general/utils/StringUtils.kt
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/layout/item_attendee.xml
  app/src/main/res/values/strings.xml
Labels: fix

#1991 feat: Add recent search query
  app/src/main/java/org/fossasia/openevent/general/search/LocationAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/search/LocationViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationViewModel.kt
  app/src/main/res/layout/fragment_search_location.xml
  app/src/main/res/layout/item_location_text.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1999 feat: Add recent search query in SearchFragment
  app/src/fdroid/java/org/fossasia/openevent/general/search/location/GeoLocationViewModel.kt
  app/src/fdroid/java/org/fossasia/openevent/general/search/location/LocationServiceImpl.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/location/LocationAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/search/location/LocationService.kt
  app/src/main/java/org/fossasia/openevent/general/search/location/LocationViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/search/location/PlaceSuggestionViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/search/location/PlaceSuggestionsAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/recentsearch/RecentSearchAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/search/recentsearch/RecentSearchViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/search/time/SearchTimeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/time/SearchTimeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/type/SearchTypeAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/search/type/SearchTypeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/type/SearchTypeViewModel.kt
  app/src/main/res/layout-land/fragment_search.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_time.xml
  app/src/main/res/layout/fragment_search_type.xml
  app/src/main/res/layout/item_recent_search.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/playStore/java/org/fossasia/openevent/general/search/location/GeoLocationViewModel.kt
  app/src/playStore/java/org/fossasia/openevent/general/search/location/LocationServiceImpl.kt
  app/src/playStore/java/org/fossasia/openevent/general/welcome/WelcomeViewModel.kt
Labels: feature

#1993 fix: Snackbar message in profile
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt
Labels: fix

#2004 feat: Ask for login/sign up at start
  app/src/fdroid/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
  app/src/main/res/layout/fragment_auth.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
  app/src/playStore/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
Labels: feature

#2000 feat: Improve login section
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/utils/StringUtils.kt
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/layout/fragment_auth.xml
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2005 feat: Add crop image in profile fragment
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/auth/CropImageFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/utils/ImageUtils.kt
  app/src/main/res/drawable/ic_crop.xml
  app/src/main/res/drawable/ic_image.xml
  app/src/main/res/drawable/ic_trash.xml
  app/src/main/res/layout/dialog_edit_profile_image.xml
  app/src/main/res/layout/fragment_crop_image.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2008 feat: Implement location feature in f-droid build
  app/src/fdroid/java/org/fossasia/openevent/general/search/location/GeoLocationViewModel.kt
  app/src/fdroid/java/org/fossasia/openevent/general/search/location/LocationServiceImpl.kt
  app/src/fdroid/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/openevent/general/OpenEventGeneral.kt
  app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
  app/src/playStore/AndroidManifest.xml
  app/src/playStore/java/org/fossasia/openevent/general/di/FlavorSpecificModules.kt
  app/src/playStore/java/org/fossasia/openevent/general/welcome/WelcomeViewModel.kt
Labels: feature

#2014 fix(UI): Search fragment layout (#2003)
  app/src/main/res/drawable/background_fragment_search.xml
  app/src/main/res/layout/fragment_search.xml
Labels: fix

#2007 feat: Add toolbar for fragments + animation
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt
  app/src/main/java/org/fossasia/openevent/general/utils/extensions/ViewExt.kt
  app/src/main/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
  app/src/main/res/layout/fragment_events.xml
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/fragment_orders_under_user.xml
Labels: feature

#2016 fix: events refresh
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
Labels: fix

#2017 feat: Ask for rating on first order
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
  app/src/main/res/layout/dialog_rate_us.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2010 feat: Add zip in multiple network calls
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedViewModel.kt
  app/src/main/res/layout/item_card_similar_events.xml
Labels: feature

#2019 chore(deps): Bump logging-interceptor to 4.0.0 and fix errors
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/auth/RequestAuthenticator.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
Labels: dependencies

#2022 fix: Fix distorted image
  app/src/main/res/drawable/background_fragment_search.xml
  app/src/main/res/layout/fragment_search.xml
Labels: fix

#1998 feat: Update read status and apply filter for notifications
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/7.json
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/notification/Notification.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationApi.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationDao.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationService.kt
  app/src/main/java/org/fossasia/openevent/general/notification/NotificationViewModel.kt
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2020 fix: Reloading SpeakersCall and Speakers
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallViewModel.kt
  app/src/main/res/layout/fragment_search_results.xml
Labels: fix

#2024 chore: Release v0.5.0
  .github/release-drafter.yml
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallViewModel.kt
  app/src/main/res/layout/fragment_search_results.xml
Labels: chore
