Repository fossasia/open-event-attendee-android, pull requests merged in 2019-09, with the labels that each got.

#2319 feat: Add State Information for Order
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/9.json
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/Order.kt
  app/src/main/res/layout/fragment_attendee.xml
Labels: feature

#2344 chore: Bump stripe from 10.4.3 to 11.0.5 and fix errors
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
Labels: dependencies

#2345 fix: App link intent appear when clicking on Terms and Policy Section
  app/src/main/AndroidManifest.xml
Labels: fix

#2346 fix: Use event ID in favorite remove API call
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
Labels: fix
