Repository fossasia/open-event-attendee-android, pull requests merged in 2019-04, with the labels that each got.

#1514 chore: Bump version code and change version name
  app/build.gradle
Labels: chore

#1516 chore: reduce app size by removing mapbox
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
  app/src/main/res/drawable/header.png
  app/src/main/res/drawable/ic_open_event.png
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/layout/fragment_order_details.xml
  app/src/main/res/layout/fragment_search_location.xml
Labels: chore

#1479 feat: Sort tickets and grey out old tickets.
  app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersViewHolder.kt
  app/src/main/res/layout/content_no_tickets.xml
  app/src/main/res/layout/fragment_orders_under_user.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1272 refractor: Replace all hard-coded string messages
  app/src/main/java/org/fossasia/openevent/general/about/AboutEventViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values/strings.xml
Labels: chore, refactor

#1512 fix: capitalised words in EditProfileFragment
  app/src/main/res/layout/fragment_edit_profile.xml
Labels: enhancement, fix

#1508 feat: add external event url menu option in EventDetailsFragment
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/res/menu/event_details.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1492 feat: Add no internet view on TicketsFragment
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/res/layout/fragment_tickets.xml
Labels: enhancement, feature

#1238 fix: horizontal search view doesn't take up whole screen
  app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
Labels: fix

#1500 fix: event title being cut off in EventDetailsFragment
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/res/layout/content_event.xml
Labels: fix

#1518 feat: add chips for search
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/res/color/text_color_chip_state_list.xml
  app/src/main/res/layout/fragment_search_results.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, feature

#1356 feat: Added Hindi Translations
  app/src/main/res/values-hi-rIN/strings.xml
Labels: chore

#1506 chore: Move appbar logic to utils.
  app/src/main/java/org/fossasia/openevent/general/about/AboutEventFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTimeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt
Labels: chore, refactor

#1536 chore: Raise minSdk to Lollipop
  app/build.gradle
Labels: chore

#1490 fix: about event view on collapsing layout
  app/src/main/java/org/fossasia/openevent/general/about/AboutEventFragment.kt
  app/src/main/res/drawable/scrim_shape.xml
  app/src/main/res/layout/fragment_about_event.xml
  app/src/main/res/values/dimens.xml
Labels: enhancement, fix

#1539 fix: set chip layout position at top of SearchResultsFragment
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/res/layout/fragment_search_results.xml
Labels: fix

#1533 fix: set secondary color to editprofile buttons
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/values/strings.xml
Labels: fix

#1494 fix: Improve horizontal likes fragment
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/res/layout/fragment_favorite.xml
Labels: fix

#1547 fix: Hide chip group when there is no internet
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/res/layout/fragment_search_results.xml
Labels: fix

#1534 fix: Disable Google Credentials Sign In leading to crash
  app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
Labels: fix

#1558 fix: remove html tags before isNullOrEmpty
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Labels: fix

#1549 fix: Make chip not clickable while fetching events
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
Labels: fix

#1562 fix(ui): random increase in size of Edit FAB
  app/src/main/res/layout/fragment_edit_profile.xml
Labels: fix, ui

#1560 fix: Removed Bold Style in Button
  app/src/main/res/values/styles.xml
Labels: fix

#1564 fix: improve favorite fragment layout
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/res/layout/fragment_favorite.xml
Labels: fix

#1521 feat: add event types for search
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/event/types/EventType.kt
  app/src/main/java/org/fossasia/openevent/general/event/types/EventTypesApi.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/res/layout/event_type_list.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_type.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1316 feat: Share event details along with image
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/openevent/general/common/RecyclerViewCallbacks.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsListAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/res/xml/file_provider.xml
Labels: feature

#1570 fix: Make back button in searchtypefragment work.
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt
Labels: fix

#1575 chore(refactor): refactor to Anko Snackbars
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
  app/src/main/java/org/fossasia/openevent/general/about/AboutEventFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
Labels: chore, refactor

#1571 fix: retain value of time and type of event
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTimeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTimeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#1568 fix: Replace setting toolbar with setToolbar
  app/src/main/java/org/fossasia/openevent/general/about/AboutEventFragment.kt
Labels: fix

#1498 feat: add Event Location
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/event/location/EventLocation.kt
  app/src/main/java/org/fossasia/openevent/general/event/location/EventLocationApi.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationViewModel.kt
  app/src/main/res/layout/fragment_search_location.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1586 feat: display shimmer while loading event locations
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationViewModel.kt
  app/src/main/res/layout/fragment_search_location.xml
  app/src/main/res/layout/placeholder_item_event_location.xml
Labels: feature

#1589 fix: crash on login fragment
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
Labels: fix

#1565 feat: add Event Types Chips
  app/src/main/java/org/fossasia/openevent/general/event/types/EventType.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt
  app/src/main/res/layout/fragment_search_results.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/styles.xml
Labels: feature

#1605 fix: convert null description to empty description
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Labels: fix

#1599 fix: default currency in case of no currency
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Labels: fix

#1578 feat: Add option to change password.
  app/src/main/java/org/fossasia/openevent/general/auth/AuthApi.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/change/ChangeRequestToken.kt
  app/src/main/java/org/fossasia/openevent/general/auth/change/ChangeRequestTokenResponse.kt
  app/src/main/java/org/fossasia/openevent/general/auth/change/Password.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsViewModel.kt
  app/src/main/res/layout/dialog_change_password.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings.xml
Labels: feature

#1580 feat: Add log out dialog in settings fragment.
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
Labels: feature

#1572 feat: reimplement google smart lock for login
  app/src/fdroid/java/org/fossasia/openevent/general/auth/SmartAuthUtil.kt
  app/src/fdroid/java/org/fossasia/openevent/general/auth/SmartAuthViewModel.kt
  app/src/fdroid/java/org/fossasia/openevent/general/search/SmartAuthViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/playStore/java/org/fossasia/openevent/general/auth/SmartAuthUtil.kt
  app/src/playStore/java/org/fossasia/openevent/general/auth/SmartAuthViewModel.kt
Labels: feature

#1510 fix: Unnecessary calls for social links and similar events
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt
  app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt
Labels: fix

#1615 fix: strip raw html evenr description before sharing
  app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
Labels: fix

#1583 fix: Move network logic into ViewModel with Broadcast Receiver
  app/src/main/java/org/fossasia/openevent/general/connectivity/MutableConnectionLiveData.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
  app/src/main/res/values/strings.xml
Labels: fix

#1601 feat: add event feedback
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/event/feedback/Feedback.kt
  app/src/main/java/org/fossasia/openevent/general/event/feedback/FeedbackApi.kt
  app/src/main/java/org/fossasia/openevent/general/event/feedback/FeedbackRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/event/feedback/FeedbackViewHolder.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/item_feedback.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1606 feat: Add Speakers Section
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/2.json
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/Speaker.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerApi.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerDao.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerService.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerWithEvent.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerWithEventDao.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/item_speaker.xml
Labels: feature

#1634 feat: Changed speaker item layout and made rv horizontal.
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/item_speaker.xml
Labels: feature

#1628 fix: Remove html tags from speaker's bio.
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerViewHolder.kt
Labels: fix

#1636 chore: Move flask filter logic from ViewModels to Services
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeService.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
Labels: chore

#1594 feat: MapBox AutoComplete Places
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/java/org/fossasia/openevent/general/search/PlaceSuggestionViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/search/PlaceSuggestionsAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationViewModel.kt
  app/src/main/res/layout/fragment_events.xml
  app/src/main/res/layout/fragment_search_location.xml
  app/src/main/res/layout/item_place_suggestion.xml
Labels: feature

#1642 feat: Add Free Stuff Filter
  app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_done.xml
  app/src/main/res/drawable/ic_filter.xml
  app/src/main/res/layout/fragment_search_filter.xml
  app/src/main/res/menu/search_filter.xml
  app/src/main/res/menu/search_results.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1650 feat: search on clicking hashtag
  app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsListAdapter.kt
Labels: feature

#1662 fix: Block descendant focusability on sections in event detail fragment
  app/src/main/res/layout/content_event.xml
Labels: fix

#1665 fix: Disable API logs for release build
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
Labels: fix

#1644 feat: Add speaker fragment
  app/src/main/java/org/fossasia/openevent/general/common/RecyclerViewCallbacks.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/Speaker.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerApi.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerDao.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerService.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerViewModel.kt
  app/src/main/res/layout/fragment_speaker.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: feature

#1648 fix: Improve Search Type Layout
  app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt
  app/src/main/res/layout/event_type_list.xml
  app/src/main/res/layout/fragment_search_type.xml
Labels: fix

#1660 fix: Enable reloading when pulling in EventsFragment
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
Labels: fix

#1661 fix: Repeating HashTags
  app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
Labels: fix

#1623 feat: Add Event FAQs
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/event/faq/EventFAQ.kt
  app/src/main/java/org/fossasia/openevent/general/event/faq/EventFAQApi.kt
  app/src/main/java/org/fossasia/openevent/general/event/faq/EventFAQFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/faq/EventFAQViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/faq/FAQRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/event/faq/FAQViewHolder.kt
  app/src/main/res/layout/fragment_event_faq.xml
  app/src/main/res/layout/item_faq.xml
  app/src/main/res/menu/event_details.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1639 feat: Add submit feedbacks
  app/src/main/java/org/fossasia/openevent/general/auth/UserId.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/event/feedback/Feedback.kt
  app/src/main/java/org/fossasia/openevent/general/event/feedback/FeedbackApi.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/dialog_feedback.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1669 fix: Add no-internet card on SearchTypeFragment
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeViewModel.kt
  app/src/main/res/layout/fragment_search_type.xml
Labels: fix

#1668 fix: Prevent making a lot of fragment on backstack when filtering search result
  app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt
Labels: fix

#1654 feat: Add sponsors section
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/Sponsor.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorApi.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorDao.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorService.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorUtil.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorWIthEvent.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorWithEventDao.kt
  app/src/main/res/drawable/foreground_black_blur.xml
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/item_social_link.xml
  app/src/main/res/layout/item_sponsor.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1641 refactor: Use Kotlin only safe args plugin
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/res/navigation/navigation_graph.xml
Labels: chore, refactor

#1684 fix: Make search button possible
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
Labels: fix

#1667 feat: Add Sort By Filters
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_search_filter.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1687 feat: display shimmer while loading event types
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeViewModel.kt
  app/src/main/res/layout/fragment_search_type.xml
  app/src/main/res/layout/placeholder_item_event_type.xml
Labels: feature

#1685 feat: Add sponsors section to show details of all sponsor
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorsDetailAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorsViewModel.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/fragment_sponsors.xml
  app/src/main/res/layout/item_sponsor_detail.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1659 fix: Make chip not checkable and search possible
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/res/layout/fragment_favorite.xml
Labels: fix

#1647 feat: Add Session Sections
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/Microlocation.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/Session.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionApi.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionType.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewHolder.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/item_session.xml
Labels: feature

#1557 fix: show ErrorSnackMessage in EventDetailsCoordinatorLayout
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt
Labels: fix

#1680 feat: Add Location,Type, time filters
  app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTimeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_star_border.xml
  app/src/main/res/drawable/ic_time.xml
  app/src/main/res/layout/fragment_search_filter.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature
