Repository fossasia/open-event-attendee-android, pull requests merged in 2019-10, with the labels that each got.

#2369 chore: Baseline master to dev
  scripts/update-apk.sh
Labels: chore

#2370 chore: Update changelog, screenshots, version code for 0.8
  README.md
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/15.txt
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_2.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_4.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_5.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_6.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_7.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_8.jpg
Labels: chore

#2371 chore: Release 0.8.0
  .travis.yml
  CONTRIBUTING.md
  README.md
  app/build.gradle
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/9.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/Attendee.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeConverter.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeId.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeIdConverter.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/ListAttendeeConverter.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDao.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/order/ExpiredOrderFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/Order.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDao.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDataSource.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDataSourceFactory.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/paypal/Paypal.kt
  app/src/main/java/org/fossasia/openevent/general/paypal/PaypalApi.kt
  app/src/main/java/org/fossasia/openevent/general/paypal/PaypalPaymentResponse.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/utils/Error.kt
  app/src/main/java/org/fossasia/openevent/general/utils/ErrorUtils.kt
  app/src/main/res/layout-land/item_card_order_details.xml
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/layout/fragment_expired_order.xml
  app/src/main/res/layout/fragment_order_details.xml
  app/src/main/res/layout/fragment_orders_under_user.xml
  app/src/main/res/layout/item_card_order_details.xml
  app/src/main/res/values-bn-rIN/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings.xml
  build.gradle
  fastlane/metadata/android/en-US/changelogs/15.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_2.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_4.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_5.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_6.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_7.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_8.jpg
  fastlane/metadata/android/en-US/short_description.txt
Labels: chore, release

#2372 chore: Shorten short description
  fastlane/metadata/android/en-US/short_description.txt
Labels: chore

#2374 fix: Google API Error for screenshots
  README.md
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_7.jpg
Labels: fix

#2379 fix: Notification dot visibility logic
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
Labels: fix

#2377 chore: dry run on dev to master merge pr
  scripts/update-apk.sh
Labels: chore

#2394 chore: update travis ci badges
  README.md
Labels: chore

#2391 fix: Similar events collapsing
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Labels: fix

#2406 chore(deps): bump lifecycle_version from 2.2.0-beta01 to 2.2.0-rc01
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/ExpiredOrderFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/type/SearchTypeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
Labels: dependencies

#2407 chore: Baseline master to dev
  README.md
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_7.jpg
  fastlane/metadata/android/en-US/short_description.txt
Labels: chore
