Repository fossasia/open-event-attendee-android, pull requests merged in 2019-07, with the labels that each got.

#2035 feat: Add donation ticket
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketIdAndQtyWrapper.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
  app/src/main/res/layout/fragment_tickets.xml
  app/src/main/res/layout/item_ticket.xml
  app/src/main/res/layout/item_ticket_details.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2031 feat: Add ticket details
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt
  app/src/main/res/layout/item_ticket.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2036 fix: app crashes navigating to AuthFragment from EventDetailsFragment
  app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/utils/extensions/FragmentExt.kt
Labels: fix

#2034 feat: Add placed and pending order
  app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
  app/src/main/java/org/fossasia/openevent/general/utils/DataBindingAdapters.kt
  app/src/main/res/layout/item_card_order.xml
  app/src/main/res/values/colors.xml
Labels: feature

#2037 feat: Verify email with app
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthApi.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EmailVerificationResponse.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/RequestEmailVerification.kt
  app/src/main/java/org/fossasia/openevent/general/auth/Token.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
  app/src/main/res/values/strings.xml
Labels: feature

#2039 fix: Back button in location fragment
  app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationFragment.kt
Labels: fix

#2032 fix: wrong order status
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
Labels: fix

#2044 fix: redundant code after zip
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedViewModel.kt
Labels: fix

#2012 feat: Add pagination
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventApi.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsListAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/paging/EventsDataSource.kt
  app/src/main/java/org/fossasia/openevent/general/event/paging/EventsDataSourceFactory.kt
  app/src/main/res/layout/fragment_events.xml
Labels: feature

#2042 fix: app crashes in TicketsFragment
  app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
Labels: fix

#2055 fix: App crashes on first time sign in
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#2057 refactor: Event field, organizer to owner
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/7.json
  app/src/main/java/org/fossasia/openevent/general/event/Event.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/res/layout-land/item_card_order_details.xml
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/item_card_order_details.xml
Labels: chore, refactor

#2060 feat: Add loading indicator in EventDetailsFragment
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/res/layout/content_event.xml
Labels: feature

#2062 feat: Add take image for editting profile
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/EditSpeakerFragment.kt
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/layout/dialog_edit_profile_image.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2040 chore: Simplify signing apk, update apk generation and README
  .travis.yml
  README.md
  app/build.gradle
  build.gradle
  scripts/prep-key.sh
  scripts/update-apk.sh
Labels: chore

#2068 fix: Show skip button when only needed
  app/src/fdroid/java/org/fossasia/openevent/general/search/location/GeoLocationViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationFragment.kt
  app/src/main/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
  app/src/main/res/layout/fragment_auth.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#2070 fix: Retain events in EventsFragment
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/res/layout/fragment_events.xml
Labels: fix

#2069 feat: Add filtering and sorting dialog
  app/src/main/java/org/fossasia/openevent/general/order/ExpiredOrderFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
  app/src/main/res/layout/dialog_filter_order.xml
  app/src/main/res/layout/fragment_expired_order.xml
  app/src/main/res/layout/fragment_orders_under_user.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2065 fix: Malformed name of aab file
  scripts/update-apk.sh
Labels: fix

#2071 fix: Change aab name in deploy script
  scripts/update-apk.sh
Labels: fix

#2072 feat: Add pagination in search
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventApi.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsListAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchEventsDataSource.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchEventsDataSourceFactory.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchPagedListAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_search_results.xml
Labels: feature

#2066 feat: Display ticket price range and revalidate tickets
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/7.json
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/Ticket.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketDao.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketPriceRange.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketService.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/values/colors.xml
Labels: feature

#2078 feat: Add paging for fetching similar events
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/event/paging/SimilarEventsDataSource.kt
  app/src/main/java/org/fossasia/openevent/general/event/paging/SimilarEventsDataSourceFactory.kt
  app/src/main/java/org/fossasia/openevent/general/event/similarevent/SimilarEventsListAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/event/topic/EventTopicApi.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedViewModel.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/fragment_order_completed.xml
Labels: feature

#2090 fix: Password length in settings and profile fragment
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
Labels: fix

#2093 chore: Add fastlane metadata
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/metadata/android/en-US/changelogs/10.txt
  fastlane/metadata/android/en-US/changelogs/11.txt
  fastlane/metadata/android/en-US/changelogs/6.txt
  fastlane/metadata/android/en-US/changelogs/7.txt
  fastlane/metadata/android/en-US/changelogs/9.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/images/icon.png
  fastlane/metadata/android/en-US/short_description.txt
  fastlane/metadata/android/en-US/title.txt
  fastlane/metadata/android/en-US/video.txt
Labels: chore

#2089 chore: Use correct Mapbox Java SDK version
  app/build.gradle
Labels: chore

#2099 chore: Add screenshots in fastlane metadata and update readme
  README.md
  docs/images/screenshot_3.png
  fastlane/metadata/android/en-US/images/screenshot_1.png
  fastlane/metadata/android/en-US/images/screenshot_2.png
  fastlane/metadata/android/en-US/images/screenshot_3.png
  fastlane/metadata/android/en-US/images/screenshot_4.png
  fastlane/metadata/android/en-US/images/screenshot_5.png
  fastlane/metadata/android/en-US/images/screenshot_6.png
  fastlane/metadata/android/en-US/images/screenshot_7.png
  fastlane/metadata/android/en-US/images/screenshot_8.png
  fastlane/metadata/android/en-US/images/screenshot_9.png
Labels: chore

#2092 feat: Add more Vietnamese translation
  app/src/main/java/org/fossasia/openevent/general/about/AboutEventFragment.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
  app/src/main/res/drawable/ic_autorenew.xml
  app/src/main/res/drawable/ic_baseline_backup.xml
  app/src/main/res/drawable/ic_baseline_build.xml
  app/src/main/res/drawable/ic_create_white.xml
  app/src/main/res/drawable/ic_done.xml
  app/src/main/res/drawable/ic_speaker_black.xml
  app/src/main/res/drawable/round_button.xml
  app/src/main/res/menu/navigation_auth.xml
  app/src/main/res/menu/search.xml
  app/src/main/res/values-bn-rIN/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#2075 fix: truncated order status
  app/src/main/java/org/fossasia/openevent/general/data/Resource.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/utils/DataBindingAdapters.kt
  app/src/main/res/drawable/border_order_status.xml
  app/src/main/res/layout/item_card_order.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: fix

#2081 feat: Handle app link intent for password reset and add unit test
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthApi.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/RequestPasswordReset.kt
  app/src/main/java/org/fossasia/openevent/general/auth/ResetPasswordResponse.kt
  app/src/main/java/org/fossasia/openevent/general/auth/forgot/PasswordReset.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/utils/AppLinkData.kt
  app/src/main/java/org/fossasia/openevent/general/utils/AppLinkUtils.kt
  app/src/main/res/layout/dialog_reset_password.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/fossasia/openevent/general/AppLinkUtilsTest.kt
  app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt
Labels: feature

#2110 fix: Display unauthorization error while loading events
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/utils/AppLinkUtils.kt
  app/src/main/java/org/fossasia/openevent/general/utils/HttpErrors.kt
Labels: fix

#2112 fix: empty input username
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#2106 feat: Add paging for order
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventApi.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/order/ExpiredOrderFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDataSource.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDataSourceFactory.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersPagedListAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrdersViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
  app/src/main/res/layout/fragment_expired_order.xml
  app/src/main/res/layout/fragment_orders_under_user.xml
  app/src/main/res/values-bn-rIN/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2124 chore: fix fastlane screenshots directory
  README.md
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_1.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_3.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_4.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_5.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_6.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_7.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_8.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot_9.png
Labels: chore

#2104 feat: Fetch settings and divide events view model
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/8.json
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/StartupViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/Event.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/settings/Settings.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsApi.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsDao.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsService.kt
  app/src/main/res/layout/fragment_attendee.xml
Labels: feature

#2127 fix: Billing information from
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/layout/item_attendee.xml
Labels: fix

#2130 feat: Add searchable spinner for country name
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/res/layout/fragment_attendee.xml
Labels: feature

#2096 fix: SearchLocationFragment back press not working
  app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationFragment.kt
  app/src/main/res/layout/fragment_search_location.xml
Labels: fix

#2132 fix: Use event's time zone as default
  app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
  app/src/main/res/values/strings.xml
Labels: fix

#2129 fix: Illogical information displayed in Ticket and Event section
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeService.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/res/layout/item_attendee.xml
  app/src/main/res/layout/item_card_order_details.xml
  app/src/main/res/values/strings.xml
Labels: fix

#2097 feat: Add quantity picker for donation ticket
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/layout/item_ticket.xml
Labels: feature

#2138 fix: Add upcoming filter for similar events
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/event/topic/EventTopicApi.kt
Labels: fix

#2139 feat: Add more field to update user detail
  app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2136 fix: Make billing information compulsory for paid orders
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: fix

#2144 chore: Bump nav_version and set jvm target to 1.8
  app/build.gradle
Labels: chore

#2151 fix: bugs in Attendee Custom Form
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeApi.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/forms/FormIdentifier.kt
  app/src/main/res/layout/item_attendee.xml
Labels: fix

#2152 fix: Sort country code and country name
  app/src/main/res/values/strings-country-name.xml
Labels: fix

#2118 feat: Add log in to save favorite event
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/8.json
  app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
  app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/Event.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventApi.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDao.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/topic/EventTopicApi.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEvent.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventApi.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchResultsViewModel.kt
  app/src/main/res/layout/dialog_login_to_like.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2145 fix: Event time, price and UI for tickets
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
  app/src/main/res/layout/item_ticket.xml
  app/src/main/res/layout/item_ticket_details.xml
Labels: fix

#2158 fix: Location icon and feedback dialog
  app/src/main/res/layout/dialog_feedback.xml
  app/src/main/res/layout/fragment_search_location.xml
Labels: fix

#2143 feat: Add server configuration field for fDroid
  app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
  app/src/main/java/org/fossasia/openevent/general/di/HostSelectionInterceptor.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/settings/SettingsViewModel.kt
  app/src/main/res/layout/dialog_api_configuration.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings.xml
Labels: feature

#2161 fix: Empty search location
  app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationFragment.kt
Labels: fix

#2162 feat: Add date format for Favorite Event Fragment
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsListAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchPagedListAdapter.kt
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/item_card_favorite_event.xml
Labels: feature

#2149 feat: Add session for event
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/8.json
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventApi.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/Session.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionApi.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionService.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/EditSpeakerFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/Proposal.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallProposalFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallProposalViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/ListSpeakerIdConverter.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerApi.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerId.kt
  app/src/main/res/layout/fragment_speakers_call_proposal.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2171 fix: Update speakers and session
  app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallFragment.kt
  app/src/main/res/values/strings.xml
Labels: fix

#2178 chore: Fix travis build
  .travis.yml
Labels: chore

#2176 fix: Stop progress on error in tickets
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
Labels: fix

#2174 fix: Prevent crash on trying to edit profile image
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
  app/src/main/res/values/strings.xml
Labels: fix

#2173 fix: Empty UI in order completed fragment
  app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
Labels: fix

#2181 feat: Add string format
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/type/SearchTypeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt
  app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/res/values/strings.xml
Labels: refactor

#2117 feat: Add chaining RxJava
  app/src/main/java/org/fossasia/openevent/general/about/AboutEventViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt
Labels: enhancement, feature

#2195 chore: Fix Travis build
  .travis.yml
Labels: chore

#2192 chore: Bump version code and name v0.6.0
  app/build.gradle
Labels: chore

#2196 chore: Add fastlane changelog for v0.6.0
  fastlane/metadata/android/en-US/changelogs/12.txt
Labels: chore

#2197 chore: Move to correct directory containing metadata
  scripts/update-apk.sh
Labels: chore

#2199 fix: Array list in search type fragment
  app/src/main/java/org/fossasia/openevent/general/search/type/SearchTypeFragment.kt
Labels: fix

#2185 fix: Feedback - button and crashes
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/type/SearchTypeFragment.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/fragment_event.xml
  app/src/main/res/values/strings.xml
Labels: fix

#2200 chore: Release v0.6.1
  app/build.gradle
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/search/type/SearchTypeFragment.kt
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/fragment_event.xml
  app/src/main/res/values/strings.xml
  fastlane/metadata/android/en-US/changelogs/13.txt
  scripts/update-apk.sh
Labels: chore

#2215 feat: Open external ticket URL
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Labels: feature

#2206 feat: Add tax for tickets
  app/schemas/org.fossasia.openevent.general.OpenEventDatabase/9.json
  app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
  app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
  app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
  app/src/main/java/org/fossasia/openevent/general/event/tax/Tax.kt
  app/src/main/java/org/fossasia/openevent/general/event/tax/TaxApi.kt
  app/src/main/java/org/fossasia/openevent/general/event/tax/TaxDao.kt
  app/src/main/java/org/fossasia/openevent/general/event/tax/TaxService.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt
  app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
  app/src/main/java/org/fossasia/openevent/general/utils/HttpErrors.kt
  app/src/main/res/layout/fragment_attendee.xml
  app/src/main/res/layout/item_ticket.xml
  app/src/main/res/layout/item_ticket_details.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2214 fix: Date format and feedback button style
  app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
  app/src/main/res/layout/content_event.xml
  app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt
Labels: fix
