Repository fossasia/open-event-attendee-android, pull requests merged in 2020-01, with the labels that each got.

#2549 chore: bump com.diffplug.gradle.spotless from 3.26.1 to 3.27.0
  app/build.gradle
  build.gradle
Labels: chore, dependencies

#2566 chore: Add support for polish language
  app/src/main/res/values-pol/string.xml
Labels: chore

#2571 chore: Add Chinese (Simplified) Language!
  app/src/main/res/values-zh-rCN/strings.xml
Labels: chore

#2568 chore: Add support for thai language
  app/src/main/res/values-th/string.xml
Labels: chore

#2578 chore: Revert Translation PRs
  app/src/main/res/values-pol/string.xml
  app/src/main/res/values-th/string.xml
Labels: chore

#2580 fix: Hide Event Map without coordinates
  app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
  app/src/main/res/layout/content_event.xml
Labels: fix

#2601 chore: bump com.diffplug.gradle.spotless from 3.26.1 to 3.27.1
  app/build.gradle
  build.gradle
Labels: chore

#2593 fix: Remove hardcoded strings
  app/src/main/res/layout/content_event.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_social_link.xml
  app/src/main/res/menu/order_completed.xml
  app/src/main/res/values/strings.xml
Labels: fix

#2605 fix: Scrolling in change password
  app/src/main/res/layout/dialog_change_password.xml
Labels: fix

#2608 fix: Scrolling in ticket filter (#2607)
  app/src/main/res/layout/dialog_filter_order.xml
Labels: fix

#2614 chore(deps): Bump com.github.jasminb:jsonapi-converter from 0.9 to 0.10
  app/build.gradle
Labels: dependencies

#2613 fix: Search text overflows in the search field
  app/src/main/res/layout/fragment_events.xml
Labels: fix

#2606 fix: Scrolling in notification activity
  app/src/main/res/layout/fragment_notification.xml
Labels: fix

#2616 fix: made proper margin to no internet dialog
  app/src/main/res/layout/fragment_events.xml
Labels: fix
